apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  capacity:
    storage: 1Gi  # Adjust the size as needed
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc  # The storage class for EBS
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0b725c7237ad80f76 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size to match the PV
  storageClassName: ebs-sc  # Must match the PV's storageClassName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: "10.0.4.155:3306"  # External DB Host
            - name: WORDPRESS_DB_USER
              value: "wp_user"         # DB Username
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass  # Secret name where the password is stored
                  key: password     # The key for the password value in the secret
            - name: WORDPRESS_DB_NAME
              value: "wordpress_db"     # Database name for WordPress
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html  # WordPress default directory to store files
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc  # Refers to the PVC defined earlier