---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
  namespace: default
spec:
  ports:
   - port: 80
     protocol: TCP
     targetPort: 80
  selector:
    app: wordpress
  type: ClusterIP
