# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: wordpress-pv
# spec:
#   capacity:
#     storage: 1Gi  # Adjust the size as needed
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: ebs-sc  # The storage class for EBS
#   csi:
#     driver: ebs.csi.aws.com
#     volumeHandle: vol-0b725c7237ad80f76 
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wordpress-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi  # Adjust the size to match the PV
#   storageClassName: ebs-sc  # Must match the PV's storageClassName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: WORDPRESS_DB_HOST
              value: "10.0.4.155:3306"  
            - name: WORDPRESS_DB_USER
              value: "wp_user"      
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass  
                  key: password    
            - name: WORDPRESS_DB_NAME
              value: "wordpress_db"     
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"  
            limits:
              cpu: "500m"  
      #     volumeMounts:
      #       - name: wordpress-storage
      #         mountPath: /var/www/html 
      # volumes:
      #   - name: wordpress-storage
      #     persistentVolumeClaim:
      #       claimName: wordpress-pvc  

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
